### ISSUE TITLE
Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by vikumkbv** [vikumkbv/Medic#1]
We want to create guideline saying need clean code and bug free code to sent as PRs

**Comment by Jagpreet153** [comment]
Hi @vikumkbv I have added contributing.md file as pull request kindly assign this task to me and review the file...

**Comment by vikumkbv** [comment]
Hi @Jagpreet153,

I have approved your contribution. Thanks for your support

Thanks,
Vikum
